CREATE TABLE [dbo].[WorkEvent]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	[PersonId] INT NOT NULL FOREIGN KEY REFERENCES [Person]([Id]),
	[Type] INT NOT NULL FOREIGN KEY REFERENCES [WorkEventType]([Id]),
	[Date] DATE NOT NULL,
	[Duration] DECIMAL(4,2) NOT NULL,
	[Description] NVARCHAR(MAX)
)